// Mapping tattoo style names (matching DB) to representative emojis
export const STYLE_EMOJIS: Record<string, string> = {
  "3D": "🧊",
  "Abstract": "🌀",
  "Anime": "🗾",
  "Black & Grey": "⚫️⚪️",
  "Biomechanical": "🤖",
  "Blackwork": "⬛️",
  "Chicano": "🕶️",
  "Color": "🌈",
  "Cover Up": "🩹",
  "Dotwork": "▫️",
  "Fine Line": "📏",
  "Geometric": "🔷",
  "Horror": "👻",
  "Illustrative": "🎨",
  "Japanese": "🌸",
  "Lettering": "✍️",
  "Mandala": "🕉️",
  "Minimalist": "➖",
  "Neo Traditional": "🦉",
  "New School": "🚀",
  "Old School": "⚓️",
  "Ornamental": "💠",
  "Portrait": "🖼️",
  "Realism": "📸",
  "Religious": "⛪️",
  "Sketch": "✏️",
  "Surrealism": "🌙",
  "Trash Polka": "🟥",
  "Tribal": "🗿",
  "Watercolor": "💧"
};